### PR TITLE
Add meson build

### PR DESCRIPTION
**Pull request by armintoepfer**
Hi there 👋

Feel free to merge or ignore/close. I wanted to try your work, but the makefiles do not work out of the box on my machine and since I can't integrate arcane makefiles into larger projects, I added meson to enable pkgconfig. You need [meson](https://mesonbuild.com/) and [ninja](https://ninja-build.org/).
Once installed:

    mkdir build && cd build
    meson && ninja

or 

    meson build .
    ninja -C build

### CODE REVIEW

**Comment by giuliaguidi** [comment]
This is great. Thanks!

Just a heads up that the current master branch computes alignment using 8-bit integer without traceback. 

I'll notify you when the traceback is ready and I'm gonna merge it into the master branch. A 16-bit faster version should also be available soon. 

I'll update the README soon to show some API examples.

I look forward to knowing what you think about XAVIER, if it's beneficial to your projects, and how we can improve it.

**Comment by giuliaguidi** [comment]
I forgot, make sure you're using the `-mavx2` compiler flag (I just updated the makefile). On [Cori](https://docs.nersc.gov/systems/cori/), it doesn't make any difference (wrt `-march=native`) but it does on my laptop.

**Comment by armintoepfer** [comment]
Hi! Thanks for merging. Traceback is a must for my initial purpose. Do you plan to to integrate xavier as a replacement for ksw2 into minimap2? THAT would be super cool.

**Comment by giuliaguidi** [comment]
Yep! 

Both my colleague and I are traveling this week but, hopefully, we'll complete/debug the traceback in the next few days and focus on xavier's integration within mm2, flye, bella, etc. next week. 

I'll notify you as soon as this is done; we would appreciate your feedback!

Out of curiosity, which band width and/or x(z)-drop (if any) do you usually use for ksw2? Do you run it on CCS or CLR?

**Comment by armintoepfer** [comment]
My immediate use case is to use it within CCS. It's too much to explain here where exactly it is used, but I align subreads to subreads and subreads to a draft sequence. For this, I mainly use bw=500 and xdrop=100. There are other occasions without any xdrop. A mm2 integration would be the best for me to test.

**Comment by giuliaguidi** [comment]
Ok, thanks for the information!

Current results show speedups of about 6x over ksw2 with x = 100 and bw = 512 with sequences length between 5K and 50K bp (these comparisons did not include the traceback for either of the two algorithms). 

I'll get back to you as soon as the integration is done.

**Pull request merged**
